name: trading_app_hackathon
description: trading_app_hackathon

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  get: ^4.6.5 #MIT
  mrx_charts: ^0.1.3 #MIT
  intl: any #BSD - 3
  chart_sparkline: any #MIT
  http: any  #BSD-3-Clause
  xml2json:  any #MIT
  webview_flutter: any #BSD-3-Clause


flutter:


  uses-material-design: true


  assets:
   - assets/images/


